environment = "staging"
environment_short = "stg"
region = "australia-southeast1"
project_id = "application-stg-44fe6b"
application_repo_name = "github_paulvalla_tw-in-a-box-application"
application_env_git_repo_name = "github_paulvalla_tw-in-a-box-gke-application-env"
