version: 2.1
executors:
  terraform: # declares a reusable executor
    docker:
      - image: hashicorp/terraform:0.11.13
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: application_default_credentials.json

jobs:
  build:
    executor: terraform
    environment:
      PROJECT_ID: application-stg-44fe6b
      ENV: staging
    steps:
      - checkout
      - run: ls
      - run: echo $DEFAULT_APPLICATION_CREDENTIALS_FILE | base64 -d > application_default_credentials.json
      - run: terraform init -backend-config=bucket=$PROJECT_ID -backend-config=prefix=$ENV
      - run: terraform plan -var-file $ENV.tfvars -out=terraform.$ENV.plan
      - run: terraform apply terraform.$ENV.plan
